name: NPM CD
run-name: ${{ github.ref_name }}

# permissions:
#   contents: write
#   packages: write
#   attestations: write
#   id-token: write

on:
  release:
    types:
      - published

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REPO: ${{ github.repository }}
  USERNAME: ${{ github.repository_owner }}

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout Repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 🛠️ Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 📦 Install Dependencies
        run: bun install --frozen-lockfile

      - name: ⚙️ Build Artifacts
        run: bun run build

      - name: 🔀 Publish to NPM
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          bun publish --no-git-checks --access public

      - name: 🔀 Publish to GitHub
        env:
          NPM_CONFIG_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          bun publish --no-git-checks --access public --registry https://npm.pkg.github.com/${{ env.USERNAME }}
